export const JOBS = [
  {
    id: 0,
    title: "Full-Stack Developer at Stripe",
    type: "Full-time",
    companyName: "Stripe",
    locationType: "Remote",
    location: "San Francisco, California, United States",
    applicationEmail: "apply@stripe.com",
    applicationUrl: "https://stripe.com/apply",
    slug: "full-stack-developer-at-stripe-1",
    salary: 150000,
    approved: true,
  },
  {
    id: 1,
    title: "Full-Stack Developer at Vercel",
    type: "Full-time",
    companyName: "Vercel",
    locationType: "Hybrid",
    location: "San Francisco, California, United States",
    applicationEmail: "apply@vercel.com",
    applicationUrl: "https://vercel.com/apply",
    slug: "full-stack-developer-at-vercel-2",
    salary: 120000,
    approved: true,
  },
  {
    id: 2,
    title: "ChatGPT Backend Developer at OpenAI",
    type: "Part-time",
    companyName: "OpenAI",
    locationType: "On-site",
    location: "San Francisco, California, United States",
    applicationUrl: "https://openai.com/apply",
    slug: "chatgpt-backend-developer-at-openai-3",
    salary: 250000,
    approved: true,
  },
  {
    id: 3,
    title: "Intern at Coding in Flow",
    type: "Internship",
    companyName: "Coding in Flow",
    locationType: "Remote",
    applicationUrl: "https://codinginflow.com",
    slug: "intern-at-coding-in-flow-4",
    salary: 500,
    approved: true,
  },
  {
    id: 4,
    title: "Contractor at SmartDiary.co",
    type: "Contract",
    companyName: "SmartDiary.co",
    locationType: "Remote",
    applicationUrl: "https://smartdiary.co",
    slug: "contractor-at-smartdiary-co-5",
    salary: 30000,
    approved: true,
  },
];
